### ISSUE TITLE
Rejoindre Awesome CodeGouvFr ?

### ISSUE THREAD

**Issue by bzg** [betagouv/recommandations-collaboratives#242]
Bonjour, j'ai découvert votre projet à l'occasion d'une discussion avec l'incubateur des territoires.

Je me suis demandé s'il n'était pas un bon candidat pour https://code.gouv.fr/fr/awesome/.

Qu'en pensez-vous ?

**Comment by glibersat** [comment]
Hello @bzg ,

Avec plaisir sur le volet Reco-co (généralisation de notre plateforme de Recommandations collectives qui a démarrée en tant que UrbanVitaliz sur la thématique des friches). N'hésite pas à me dire comment faire ou si tu veux qu'on échange sur ça.

Merci,

Guillaume

**Comment by bzg** [comment]
Merci @glibersat pour ta réponse !  La mission logiciels libres est en train de recruter la personne qui va gérer le suivi et les développements de https://code.gouv.fr/fr/awesome/ - je note de te recontacter dès que cette personne arrive.

**Comment by bzg** [comment]
Hello @glibersat - as-tu besoin d'un coup de main pour avancer ?  A disposition si besoin !

**Comment by glibersat** [comment]
Salut @bzg , j'ai ajouté un fichier dans notre dépôt, tu peux regarder s'il convient ? Si c'est bon pour toi, je le propose sur le dépôt awesome. Merci !

**Comment by bzg** [comment]
Salut @glibersat, dispo pour aider si besoin :)  A bientôt !

**Comment by bzg** [comment]
C'est ajouté dans [ce commit](https://github.com/codegouvfr/awesome-codegouvfr/commit/4cacb3facbe4925e3af522187e30a10dc9da1744), vous devriez bientôt apparaître dans https://code.gouv.fr/fr/awesome/

Merci !

**Comment by glibersat** [comment]
Top, merci beaucoup !

**Comment by bzg** [comment]
Juste pour te confirmer que vous êtes bien référencés ici : https://code.gouv.fr/fr/awesome/

Merci encore :)
