### ISSUE TITLE
Utiliser le sender de SiteConfiguration pour les envois via Brevo

### ISSUE THREAD

**Issue by glibersat** [betagouv/recommandations-collaboratives#297]
Le `sender` n'est pas surchargé lors de l'envoi d'un email transactionnel avec Brevo, ce qui fait que le nom du portail n'apparaît pas.
Ceci n'est pas idéal pour identifier les emails dans les boites mails des destinataires

**Comment by sabinesafi** [comment]
A priori on gère directement depuis Brevo en indiquant un nom de sender dynamique.
