### ISSUE TITLE
Sur l'onglet Présentation, les thématiques ajoutées à la main ne gardent pas les majuscules

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#309]
**Décrivez le bug**
Quand on rentre un acronyme ou qu’on met une majuscule au début d’un mot (hormis le premier), ça remet tout en minuscule après validation. C'est relou pour les acronymes notamment.

**Quelle est l'adresse à laquelle le bug est arrivé ?**
sur l'onglet Présentation d'un projet

**Comment le reproduire ?**
Les étapes pour reproduire ce bug:
1. Modifier les thématiques du projet depuis l'onglet Présentation
2. Mettre des trucs en majuscules 
3. Valider
4. Sur la liste des thématiques, seule la première lettre de l'expression saisie est en majuscule.

**Comportement normal attendu**
Que ça garde la casse telle que je l'ai saisie

**Capture d'écran**
<img width="587" alt="Capture d’écran 2024-04-23 à 12 05 15" src="https://github.com/betagouv/recommandations-collaboratives/assets/16819425/124bf3e3-c546-4af7-9cef-b3bfa0384cf1">
<img width="382" alt="Capture d’écran 2024-04-23 à 12 05 26" src="https://github.com/betagouv/recommandations-collaboratives/assets/16819425/4291dca6-8ed0-4769-aa1e-79422f42f185">

**Comment by glibersat** [comment]
Le problème de garder la casse est que `Thématique` et `thématique`et `théMatique` seront considérées comme 3 mots différents. Du coup, il n'y a pas vraiment de solution pour ça qui remplisse tous les critères :(

**Comment by sabinesafi** [comment]
OK, je vois avec SOSP ce qui leur semble le plus important

**Comment by glibersat** [comment]
De news savoir si je peux fermer le ticket @sabinesafi ?
