### ISSUE TITLE
Les brouillons de recos sans ressources génèrent quand même des notifs email à la collectivité

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#316]
**Décrivez le bug**
Une collectivité a reçu une notif qui l'informe qu'elle a des recos alors qu'elles sont juste en brouillon côté UV. C'est uniquement les recos sans ressource associée qui ont été notifiées --> pas normal que ça soit notifié alors que c'est en brouillon.
[en cours de test : est-ce que ça arrive en fait quand une reco est publié puis dépubliée ou pas forcément]

**Quelle est l'adresse à laquelle le bug est arrivé ?**
https://urbanvitaliz.fr/project/773/actions

**Comment le reproduire ?**
Les étapes pour reproduire ce bug:
1. Sur un projet de test, créer une reco sans ressource attachée, la créer **en brouillon**
2. Le lendemain, regarder dans sa boîte mail de test ou sur Brevo si un mail est parti au référent et s'il liste la reco non publiée.

**Comportement normal attendu**
- Les recos en brouillon ne génèrent pas de notif email.
- Une notif email est générée quand la recos est publiée.

**Comment by glibersat** [comment]
@sabinesafi J'aurais besoin de plus d'infos. J'ai l'impression que le bug vient du fait que ça a été publié d'abord, puis dépublié 

Aussi, il y a 2 rapports de bugs dans cette carte ; et probablement pour 2 personnes différentes.
Pour le 2ème rapport (compte de recos) : le screenshot affiché est celui d'un conseiller, or, tu parles de collectivité au dessus. Tu pourrais nous apporter des précisions ?

Merci

**Comment by sabinesafi** [comment]
Pour le double bug : en effet, je vois que la carte qui sépare le bug front était resté dans Trello, je vais retirer la partie décompte de cette issue.
Pour le publié-dépublié : on avait effectivement une demande qui traînait de régler ce cas là (que ça ne génère pas de notif quand c'est publié puis dépublié immédiatement). Ça n'avait pas été évoqué sur le cas remonté ici. Je vais re-tester.

**Comment by sabinesafi** [comment]
A priori je n'ai pas reçu de notif hier donc on va clore cette issue pour le moment.
