### ISSUE TITLE
[Saisine] page déposez votre projet

### ISSUE THREAD

**Issue by PerrineRut** [betagouv/recommandations-collaboratives#319]
**Décrivez le bug**
La description qui dépasse pas 100 caractères c'est trop court

le front n'est pas clair du tout : 
Précisions sur la problématique - NE PAS LAISSER VIDE SINON BUG<br>
commentaire 
demande initiale
commentaire
select
commentaire (encore ?)

les champs sont obligatoires à remplir alors que ça se voit pas
et quand on essaie de soumettre sans avoir tout rempli, on a bien des champs qui deviennent rouge, mais ça a vidé ce que j'ai pu écrire dans les autres cases, il faut que je réécrive tout

**Quelle est l'adresse à laquelle le bug est arrivé ?**
ex: http://urbanvitaliz.fr/xxx/yyy

**Comment le reproduire ?**
Les étapes pour reproduire ce bug:
1. Aller à '...'
2. Cliquez sur '....'
3. Descendre jusqu'à '....'
4. Voir l'erreur

**Comportement normal attendu**
Décrivez nous le comportement que vous auriez souhaité

**Capture d'écran**
Si cela a du sens, pouvez-vous ajouter une ou plusieurs captures d'écrans pour nous aider à mieux comprendre le bug ?

**Votre environnement **
 - Système: [ex. Mac, Linux, Windows, iOS, Android]
 - Navigateur [ex. Firefox, Chrome, Safari]
 - Version [ex. 22]

N'hésitez pas à ajouter des informations supplémentaires si nécessaire

**Comment by Jeremy-Bojko** [comment]
- [ ] La description qui dépasse pas 100 caractères c'est trop court
- [ ] les champs sont obligatoires à remplir alors que ça se voit pas
- [ ] après soumission du formulaire incomplet, ça a vidé ce que j'ai pu écrire dans les autres cases
