### ISSUE TITLE
Saisine - Etape 2 Décrivez votre projet - le bouton Précédent ne fonctionne pas

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#327]
**Décrivez le bug**
En bas de la page, je clique sur Précédent avec l'intention de revenir à l'étape de création de compte. Ça ne fonctionne pas, la page recharge mais je reste sur l'étape 2.

**Comportement normal attendu**
Quand je clique sur Précédent ça devrait me ramener sur l'étape création de compte **avec les champs remplis**

**Comment by sabinesafi** [comment]
Et il supprime le contenu du form déjà saisi sur la page en cours, sans la quitter.
ll faudrait que ça renvoie vers la page précédente tout en sauvegardant ce qui a déjà été saisi.

**Comment by sabinesafi** [comment]
Ben ça peut arriver de vouloir modifier ses infos, c'est un classique dans les formulaires en plusieurs écrans de pouvoir faire marche arrière non ?

**Comment by Jeremy-Bojko** [comment]
Pour la partie Onboarding, il faut être connecté pour pouvoir créer un projet, donc à l'étape 1 on crée l'utilisateur et on le connecte dans la foulée, c'est pour ça qu'on ne peut pas retourner en arrière
