### ISSUE TITLE
Saisine - Etape 2 Décrivez votre projet - au clavier, impossible de passer sur le bouton radio Non pour Cartofriches

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#329]
**Décrivez le bug**
En parcourant le formulaire avec la touche Tab, ça saute le choix Non à la question cartofriches donc impossible de saisir ce choix en navigation au clavier.

**Comment by Jeremy-Bojko** [comment]
Pour pouvoir interagir avec des radios buttons, une fois que le groupe est atteint, il faut choisir la réponse souhaitée avec les flèches du clavier.
