### ISSUE TITLE
Saisine et EDL - questions et affichage des réponses qui ne correspondent pas au paramétrage

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#337]
**Décrivez le bug**
Sur l'étape 2 description du projet, j'ai plusieurs fois le champ commentaire qui s'affiche, avec un "demande initiale" au milieu.
Dans l'onglet EDL (post dépôt du projet), j'ai 2 encarts Contexte de la demande (perdus au milieu des autres catégories).
Alors que dans le paramétrage du questionnaire, j'ai bien 1 seule catégorie Contexte de la demande avec 2 questions dedans, et pas de commentaire.

**Comportement normal attendu**
Dans la saisine étape 2, suite aux questions "standard", on ne devrait avoir que les 2 questions paramétrées sur UV (demande initiale + cartofriche).
Dans l'EDL, on ne devrait avoir qu'une Catégorie Contexte, et elle devrait être afficher en première position près de la map.

**Capture d'écran**
<img width="927" alt="Capture d’écran 2024-04-30 à 11 35 59" src="https://github.com/betagouv/recommandations-collaboratives/assets/16819425/35fac181-1529-45ed-95cc-845025f07cc5">
<img width="1245" alt="Capture d’écran 2024-04-30 à 17 15 20" src="https://github.com/betagouv/recommandations-collaboratives/assets/16819425/c4284c88-0593-4a01-a908-d9656d7ecac1">
<img width="1211" alt="Capture d’écran 2024-04-30 à 17 16 10" src="https://github.com/betagouv/recommandations-collaboratives/assets/16819425/7b99b580-6138-4937-bfc2-346a2ca4c0a0">

**Comment by sabinesafi** [comment]
Hello @glibersat je vois que tu as fermé cette issue mais le problème de la catégorie "doublée" dans l'onglet EDL est toujours d'actualité. Tu veux que je crée une autre issue dédiée à ce point ?

![Image](https://github.com/betagouv/recommandations-collaboratives/assets/16819425/e07193c8-9467-4ed5-81a5-d5f745f18850)

**Comment by glibersat** [comment]
Ah oui, je n'avais pas vu qu'il y avait 2 bug report dans le même, oui je veux bien un séparé, merci
