### ISSUE TITLE
[EnCommuns] Page d'accueil à customiser

### ISSUE THREAD

**Issue by glibersat** [betagouv/recommandations-collaboratives#343]
Élements de page à customier pour le portail EnCommuns

https://docs.google.com/document/d/1omYLlUalX8rgyiM4HnKsgQUewYvzSgw31xfWAupHO0Q/edit?usp=sharing

**Comment by sabinesafi** [comment]
@Louifine le logo à utiliser dans le header (en enlevant le RF, Cerema, UV) + écrire à côté (toujours dans le header) : Accompagnement EnCommuns (quelque chose [dans ce genre là ici](https://drive.google.com/file/d/1037XZf0rMovW38cBA2GiQcwDhHgbOiqe/view))
![logoaac](https://github.com/betagouv/recommandations-collaboratives/assets/16819425/a0b07ccc-0a91-4acc-a02b-62ed067b3059)

**Comment by sabinesafi** [comment]
Quelques retours @Louifine :
- Changer le wording du CTA principal en Etre accompagné
- Mettre logo en favicon et en haut à gauche de la navigation
- Changer le titre de la page - pour l'instant il dit Page d'accueil - Accompagnement des communs, enlever le Page d'accueil
