### ISSUE TITLE
Des conseillères ont été affectées malgré elles sur un projet MEC

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#345]
**Décrivez le bug**
Sur ce projet : https://monespacecollectivite.incubateur.anct.gouv.fr/project/1235/presentation
- Salomé n'a aucun souvenir de s'y être affectée
- L'autre conseillère ne travaille pas sur le même programme ANCT donc c'est louche aussi qu'elle y soit

Est-il possible qu'elles aient été affectées malgré elles ?

**Comment by glibersat** [comment]
![image](https://github.com/betagouv/recommandations-collaboratives/assets/262663/fbd9e77c-4989-4758-9c58-ea467e2d5eed)

Je ne dis pas que ce n'est pas un bug mais c'est très improbable que ça génère un ajout "magique" et dans le CRM, je vois deux temporalités qui ne reflètent pas le comportement d'une machine.

A explorer plus

**Comment by sabinesafi** [comment]
ça me va que pour le moment on considère que c'est plus probablement une erreur humaine et si ça se reproduit, on s'y repenchera.
