### ISSUE TITLE
[Saisine] Ecran de confirmation - affichage de l'encart projet toujours cassé

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#348]
<img width="958" alt="Capture d’écran 2024-05-07 à 16 27 38" src="https://github.com/betagouv/recommandations-collaboratives/assets/16819425/a9cab15a-c482-41d0-813b-58c5ac1c08ed">

**Comment by glibersat** [comment]
@Jeremy-Bojko les icones dsfr?

**Comment by Jeremy-Bojko** [comment]
Yes c'est bien ça !
