### ISSUE TITLE
[Saisine - EDL] Ancien projet : la réponse à la question Contexte n'apparait pas dans l'EDL

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#352]
**Décrivez le bug**
Sur ce projet : https://urbanvitaliz.staging.recoconseil.fr/project/670/connaissance
La réponse à la question Contexte n'est pas remontée dans l'EDL. Pourtant elle existe ([voir le projet en prod ici](https://urbanvitaliz.fr/project/670/presentation))

**Comportement normal attendu**
La réponse à toutes les questions paramétrables de la saisine devrait apparaître dans l'onglet Contexte de la demande.

**Comment by glibersat** [comment]
Le contexte affiché correspond au champ description ; ce n'est pas une question de l'EDL.
