### ISSUE TITLE
[Saisine] Modifs mineures sur la page qui confirme le dépôt du projet

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#362]
![Image](https://github.com/betagouv/recommandations-collaboratives/assets/16819425/42913b6e-e933-4313-8d2b-d78631d2b571)

- supprimer la phrase Nous avons bien reçu votre projet (qui fait doublon avec le titre)
- rendre la boîte du projet non cliquable (l'encart en dessous de la phrase à supprimer)
- dans l'encart, les 2 icônes ne sont pas à la taille du texte qui les suit (insee, déposé aujourd'hui), elles sont plus grandes --> réduire leur taille
- transformer les bullet points en liste numérotées
- enlever le gras du texte des bullets points (seul le sous-titre au dessus reste en gras)
- modifier le libellé du premier point : Répondez aux questions suivantes pour accélérer l'étude de votre projet

**Comment by Jeremy-Bojko** [comment]
@sabinesafi pour ta remarque : 

> rendre la boîte du projet non cliquable

- [ ] Veux-tu que je change le style en enlevant les contours ? 
- [ ] Enlever l'icon de flèche au bout de la boite ?  

Car actuellement, il n'est déjà pas possible de cliquer dessus

**Comment by sabinesafi** [comment]
Ping @rkalfane : cf dernier message de Jérémy ci-dessus. 
Vu qu'on ne souhaite pas que les utilisateurs cliquent sur la boîte de leur projet depuis cette page, j'imagine qu'à minima on enlève la flèche ? comment tu vois cette boîte dans ce cas ?

**Comment by rkalfane** [comment]
Yes, virons la flèche, et sa bordure, histoire d'avoir un état neutre.

Cela dit si les gens cliquent et vont sur leur projet, tant qu'on les fait arriver sur l'EDL on est content, non ?

**Comment by sabinesafi** [comment]
@rkalfane @Jeremy-Bojko 
Je suis embêtée par le look de cet écran, il est devenu vraiment fouilli en enlevant complètement le cadre de l'encart projet 😅 
Et le mini logo au dessus est à agrandir il me semble.
Tes préconisations @rkalfane ?


![Image](https://github.com/betagouv/recommandations-collaboratives/assets/16819425/4e0a622f-c7c3-4e39-be50-e5379f892a8d)
