### ISSUE TITLE
[Saisine] ETQ utilisateur d'une autre plateforme, je dois être averti·e sur la page de login

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#375]
Actuellement, etq utilisatrice d'UV qui crée un projet sur SOSP (avec un compte jamais utilisé sur SOSP), j'arrive sur la page de login "générale" des utilisateurs déjà existants.
Mais si je me suis jamais connectée sur SOSP, je ne peux pas deviner que je dois utiliser mes identifiants UV...

Dans ce cas, rajouter la bannière prévu sur les maquettes de Rahman : 

![Image](https://github.com/betagouv/recommandations-collaboratives/assets/16819425/5685277a-25ec-4953-81e4-206211f71478)

**Comment by sabinesafi** [comment]
Ça serait possible d'indiquer uniquement la PF sur laquelle l'utilisateur a déjà un compte ?

**Comment by Jeremy-Bojko** [comment]
Guillaume, je te laisse compléter cette PR pour pouvoir alléger la liste des portails et ensuite, j'intègre tes modifications.
