### ISSUE TITLE
Paramétrer Metabase pour nos stats

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#387]
Les metrics à suivre : 
https://docs.google.com/spreadsheets/d/1U4KxlRYETF6n9uJ_7jpT1Wu_gu53lyA-3CC08VV37G0/edit?usp=drive_link

**Comment by glibersat** [comment]
@sabinesafi Est-ce que c'est le bon document ? Ou alors ça n'est pas la bonne carte ^^

**Comment by sabinesafi** [comment]
@SebastienReuiller il faudrait rajouter les indicateurs des lignes 11 à 14 du spreadsheet ci-dessus plz
