### ISSUE TITLE
[CRM] Le bouton pour Modifier le nom d'une orga ne marche pas

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#400]
**Décrivez le bug**
Depuis le CRM, sur la page d'une organisation, cliquer sur Gérer l'organisation puis Modifier sous le nom. On est renvoyé à la page de l'orga.

https://github.com/betagouv/recommandations-collaboratives/assets/16819425/44f8d918-c47a-417a-8a34-f4b64b8415af

**Comment by Jeremy-Bojko** [comment]
Cette fonctionnalité fonctionne, en revanche si cela a été remonté, il doit y avoir un sujet de wording 
=> remplacer `Modifier` par `Enregistrer les modifications` ?  (@sabinesafi )
