### ISSUE TITLE
[CMS] ETQ staff de portail je peux écrire une page cas d'usage - scénario min.

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#409]

**Comment by Louifine** [comment]
Pour la version minimale il manque : 
- un titre à la section "gallery" 
- et une section "aiguillage" avant la section témoignage 

Et en optionnel pour la version maximale de la page (aucune section n'est dépendante d'une autre), il faut dans l'ordre :
- une section gallery mais sans titre cette fois
- une section titre avec une liste à puce
- une nouvelle gallery avec titre
- et pour finir une section avec titre et champ texte







et pour finir une section avec titre et champ texte

**Comment by sabinesafi** [comment]
On commence par faire uniquement le scénario min (mais complet) et on verra pour le scénario max selon demande des utilisateur·rices.
