### ISSUE TITLE
[Saisine] Ajouter un texte d'aide pour le champ Nom du projet

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#416]
"Indiquez un nom court qui décrit le projet. Inutile d'ajouter le nom de la commune, l'adresse ou le programme."

**Comment by sabinesafi** [comment]
@Louifine @glibersat je vois pas cette modif en prod non plus

**Comment by glibersat** [comment]
@Louifine ?

**Comment by Louifine** [comment]
Il me semble bien avoir fait ça, je regarde de suite !

**Comment by sabinesafi** [comment]
C'est bon c'est visible en prod :)
