### ISSUE TITLE
ETQ collectivité, le dropdown de mes projets affiche l'adresse au lieu de la commune

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#417]
ETQ collectivité (et souvent etq chef de projet VA sur MEC), je navigue entre mes projets depuis un dropdown dans le header.

2 problèmes avec ce dropdown : 
- Il affiche le contenu du champ adresse au lieu du nom de la commune
- Il affiche le nom du projet en première info au lieu du nom de la commune.

![Image](https://github.com/betagouv/recommandations-collaboratives/assets/16819425/f5236357-5069-4adc-97e3-475b353d335c)

Comportement attendu : 
- Afficher le nom de la commune et non pas l'adresse
- Inverser l'affichage du nom du projet et de la commune, de manière à ce que la commune soit l'info la plus importante.

**Comment by sabinesafi** [comment]
On ets d'accord que cette carte n'est pas encore passée en prod @glibersat ? le problème est toujours présent.
<img width="1261" alt="Capture d’écran 2024-06-21 à 14 25 11" src="https://github.com/betagouv/recommandations-collaboratives/assets/16819425/d84b91f8-93dd-4031-a030-15ef96df1f42">

**Comment by glibersat** [comment]
Si elle l'est, il y a du y avoir une régression alors! cc @Jeremy-Bojko

**Comment by sabinesafi** [comment]
Je fais revenir la carte dans le backlog car le problème est toujours là
