### ISSUE TITLE
Dans les mails qui notifient le dépôt d'un nouveau projet, le déposant collectivité n'est plus affiché

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#455]
<img width="884" alt="Capture d’écran 2024-06-03 à 16 39 38" src="https://github.com/betagouv/recommandations-collaboratives/assets/16819425/8418ad42-ba5e-4914-be1e-edce3f77db49">

Depuis au moins plusieurs jours, le "déposé par :" reste vide.

**Comment by sabinesafi** [comment]
Glib : regarder dans l'appel Brevo si on va bien chercher au bon endroit

**Comment by SebastienReuiller** [comment]
@sabinesafi , c'est le template "Alerte conseillers d’un nouveau projet sur le territoire" ? Si c'est bien le cas, les paramètres passés sont :
`{'site_name': 'Example', 'site_domain': 'example.com', 'legal_address': '',
'dashboard_url':
'https://example.com/projects/?sesame=AAAABAfuuIWu_iAKq4FmeMWB', 'project':
{'name': 'Restauration grange', 'org_name': 'Orga', 'url':
'https://example.com/project/1/?sesame=AAAABAfuuIWu_iAKq4FmeMWB', 'commune':
{'postal': '37220', 'name': 'PANZOULT', 'department': {'code': '37', 'name':
'Indre-et-Loire'}}}}`

J'ai un doute sur le fait que ça ai déjà fonctionné.

**Comment by SebastienReuiller** [comment]
Le problème vient du fait que le champs [orga_name](https://github.com/betagouv/recommandations-collaboratives/blob/263138b4c7e78c9a16ade4a2310419b24086877d/recoco/apps/projects/models.py#L297) n'est plus rempli par la nouvelle saisine.
@glibersat, à voir si on remplace tout simplement [ici](https://github.com/betagouv/recommandations-collaboratives/blob/6c472f7c51cb49e779554bda3950b8b53beb3603/recoco/apps/communication/digests.py#L387) `project.org_name` par  `submitted_by.profile.organization.name`.
