### ISSUE TITLE
ETQ collectivité, j'ai reçu le mail de rappel C ET l'ancien mail de rappel sur un même projet/même reco

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#472]
Le mail C, c'est sans doute normal que je le reçoive. L'ancien mail de rappel il ne devrait plus partir par contre.

Ancien mail qui ne devrait plus partir : 
![screencapture-mail-google-mail-u-0-2024-06-17-14_30_06](https://github.com/betagouv/recommandations-collaboratives/assets/16819425/49a0bb3d-d0af-4039-83c5-4ed38c106c8c)

Mail C reçu au même moment : 
![screencapture-mail-google-mail-u-0-2024-06-17-15_01_44](https://github.com/betagouv/recommandations-collaboratives/assets/16819425/44daa95e-89c5-4e32-9b05-c2dfc54a618f)

**Comment by sabinesafi** [comment]
@glibersat j'ai pas mis le bon screenshot 😅 je corrige

**Comment by glibersat** [comment]
@sabinesafi est-ce que ça n'est pas le mail B et C ça plutôt qu'un vieux ?

**Comment by sabinesafi** [comment]
@glibersat je vois dans Brevo que c'est le template #11 qui correspond à l'ancien mail de rappel. Mais c'est vrai que le B avait vraiment la même tête, tu penses que pour le mail B on a brutalement repris le même template ? Si oui, c'est "juste" une question de délai avant envoi du mail C ?

**Comment by glibersat** [comment]
C'est ce que je suspecte oui !

**Comment by sabinesafi** [comment]
je vois dans l'admin que le mail C est réglé sur 6 mois pour UV et SOSP à minima. Tu peux vérifier que le mail B est toujours à 6 semaines stp ? là il semble partir à 6 mois aussi du coup.

**Comment by sabinesafi** [comment]
En fait j'ai l'impression que le mail B continue à partir ad vitam eternam alors que [cette issue](https://github.com/betagouv/recommandations-collaboratives/issues/386) devait régler le problème. S'il est sur 10 semaines = 60 jours, effectivement à un moment ça tombe en même temps que le mail C. @glibersat
