### ISSUE TITLE
[CRM] Dans la page Index des thématiques, dans la colonne Recommandations, je veux voir la liste des projets concernés et non pas la liste des recos

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#543]
https://urbanvitaliz.fr/crm/topics

- colonne Projet : afficher [Ville - Nom du projet] qui envoie vers le projet (la Présentation) - Thématique attachée au projet
- colonne Reco : actuellement ça liste toutes les recos qui ont la thématique en question (y compris si plusieurs recos avec cette thématique sur 1 même projet). Chez SOSP elle veulent accéder au projet qui a cette thématique --> Afficher Reco (Ville - Nom du projet) qui envoie vers le projet (la Présentation) - Thématique attachée à une reco du projet

**Comment by Louifine** [comment]
@glibersat remplacer les valeurs de la liste par des objets pour pouvoir utiliser les projects dans le fichier topics.html dans la partie crm de l'app
