### ISSUE TITLE
Refonte de la navigation au sein d'un projet

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#572]
[Maquettes](https://www.figma.com/design/DZYeKsolegotgt1IhonSSH/Navigation?node-id=103-605&t=ULyIAgI5nPQuM4fM-0) 
Attention, dans un premier temps préparer le front et y'aura un peu de taf de back pour supprimer la notion de projet actif dans un 2è temps

### Drop down avec le nom du projet
La première barre de nav affiche le projet sur lequel on est. C'est un dropdown qui n'affiche pas les mêmes choses selon les utilisateurs : 
- etq porteur de projet, je vois tous mes projets sur ce portail
- etq conseiller·e, je vois tous les projets sur lesquels je suis positionné conseiller ou obs
- etq invité·e qui n'a pas accepté de me positionner, je vois le nom hors drop down
- etq staff, je vois les 5 derniers projets que j'ai visités.

Le dernier point demande du back, et il y en aura de toute façon besoin pour [la refonte du pousse ressource](https://github.com/betagouv/recommandations-collaboratives/issues/571). Donc éventuellement, commencer sans afficher de drop down aux staffs (juste afficher le nom du projet) et on l'ajoutera après.

⚠️ Couper les noms de projets de manière à ce que l'ensemble nom commune + projet ne dépasse pas une cinquantaine de caractères

### 1ère nav - boutons à droite
- ETQ porteur de projet, j'ai le bouton Inviter
- ETQ conseiller·e, j'ai les boutons Inviter + Positionnement conseiller
- ETQ staff, j'ai les boutons Positionnement conseiller + CRM

### Bouton Inviter
On peut réutiliser la popup existante d'invitation présente plus bas sur la page. 
ETQ staff et conseiller·e, je dois avoir le choix entre inviter un membre Porteur de projet ou Conseiller (le porteur de projet ne peut pas inviter de conseiller). Rajouter un bouton radio ? Wording possible : 
* Inviter cette personne en tant que : Porteur de projet ou partenaire / Conseiller·e

### Affichage des onglets lockés
Les règles d'affichage des onglets selon les rôles sont les mêmes qu'actuellement.
ETQ conseiller·e non positionné·e, je vois les 3 derniers onglets lockés. Dès que je passe la souris dessus, ça affiche l'infobulle *Pour accéder à cet onglet, devenez conseiller ou observateur du projet* (idéalement affichage immédiat au passage de la souris). Au clic sur l'infobulle (on peut cliquer dans une infobulle sans qu'elle s'en aille ?) ça ouvre la popup de positionnement au bout de la barre de nav.

### Remplacer les bandeaux dans la nav 
 2 bandeaux sont actuellement affichées entre les 2 barres de nav : 
- celui pour conseiller ou staff non positionné sur un projet, qui m'invite à me positionner
- celui pour tout utilisateur qui consulte un projet en pause.

Dans les 2 cas, dorénavant on encadre toute la fenêtre + petit bandeau collé sous la 2ème barre de nav (couleurs différentes selon le cas).

**Comment by Jeremy-Bojko** [comment]
Link to #641 !

**Comment by sabinesafi** [comment]
Ça fait une grrrrosse issue, à voir si on découperait ? par exemple une issues pour chaque barre de nav + une pour les bandeaux/encadrements de page. A toi de me dire ce qui t'arrange Jérémy
