### ISSUE TITLE
Image logo de mauvaise qualité 

### ISSUE THREAD

**Issue by louis-vgn** [betagouv/recommandations-collaboratives#573]
Le site de la mission logiciels libres a ajouté ce logiciel dans son catalogue `awesome` (https://code.gouv.fr/fr/awesome/). 

L’image du logo de Recoco [que l’on récupère](https://github.com/codegouvfr/awesome-codegouvfr/blob/main/dist/recoco_publiccode.yml#L37) est de mauvaise qualité, surtout comparé aux logos des autres logiciels.

Pourriez-vous ajouter une image logo de meilleure qualité ?

**Comment by glibersat** [comment]
Hello @louis-vgn , je viens de faire une PR sur le dépôt Awesome :)

https://github.com/codegouvfr/awesome-codegouvfr/pull/31
