### ISSUE TITLE
[summer cleaning] retirer css inline

### ISSUE THREAD

**Issue by Louifine** [betagouv/recommandations-collaboratives#581]
4 types de css inline : 
- à changer par des classes bootstrap
- à enlever une fois le chargement de bootstrap utilities effectif (font-style=marianne)
- des pages statiques => réfléchir à la méthode de ''rangement'' des classes remplacant le css inline
- des pages du crm, gère-t-on ce cas ?

**Comment by Jeremy-Bojko** [comment]
Apparemment dans les imports ds Bootstrap il faut se passer de reboot

```scss
@import "../node_modules/bootstrap/scss/utilities"; /*On garde*/
@import "../node_modules/bootstrap/scss/containers";
@import "../node_modules/bootstrap/scss/reboot"; /*Apparement on garde pas */
@import "../node_modules/bootstrap/scss/grid";
@import "../node_modules/bootstrap/scss/helpers";
@import "../node_modules/bootstrap/scss/utilities/api";
```
