### ISSUE TITLE
Intégration de DS - éléments d'interface

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#604]
Ajout d'encarts ou d'étiquettes sur : 
- la page de la ressource concernée (non cliquable),
- le pousse-reco, dans la carte de la ressource remontée par la recherche,
- la reco elle-même dans la liste de la page Recommandations
- la popup de la reco

[Maquettes ici](https://www.figma.com/design/uCaubzjzYorSHx1KY5Ob0q/MEC---Pr%C3%A9-remplir-un-dossier-de-financement?node-id=236-2486&t=YrMSuyQOzgxYxfax-1)

**Comment by Jeremy-Bojko** [comment]
Intégration envoyée vers Matthieu pour besoin d'un échange et d'élément back pour finaliser
