### ISSUE TITLE
Ressources partagées : mettre en place du Copy-on-write

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#635]

**Comment by bastien-rcc** [comment]
comportement attendu : 

Un site A crée une ressource R.
Un site B publie cette ressource R.

Tant que la ressource n'est pas **éditée** par le site B, on la considère comme _miroir_ : 
Lorsque le site A décide de supprimer cette ressource, alors on refuse car elle est déjà partagée.
Lorsque le site B décide de supprimer cette ressource, alors on déréférence ce site de la ressource.

A partir du moment où le site B édite la ressource, on la copie et la référence au site B.
On garde une trace de l'origine de la ressource, en l’occurrence ici le site A.

**Comment by sabinesafi** [comment]
@glibersat @bastien-rcc 
- comment fait le portail A quand il a besoin de supprimer une ressource dans ce cas ?
- qu'est-ce qui se passe quand le portail A modifie la ressource ?

En l'occurrence, Salomé me dit que chez UV, plutôt que supprimer une ressource, elles vident le contenu, passent en brouillon et réutilisent la structure pour une prochaine ressource. On peut leur dire d'arrêter de faire ça mais d'une façon ou d'une autre, le portail A doit pouvoir à minima modifier/repasser en brouillon et idéalement supprimer sa ressource.

**Comment by glibersat** [comment]
@sabinesafi La première étape est de bloquer ce qui ne devrait pas arriver (ce qu'on fait là) et on pourra ensuite ajouter des comportements plus intelligents pour les cas que tu cites. En revanche, en effet, blanchir et repasser en brouillon, on ne pourra rien faire, faudrait arrêter de faire ça :)

> @glibersat @bastien-rcc
> 
>     * comment fait le portail A quand il a besoin de supprimer une ressource dans ce cas ?
> 
>     * qu'est-ce qui se passe quand le portail A modifie la ressource ?
> 
> 
> En l'occurrence, Salomé me dit que chez UV, plutôt que supprimer une ressource, elles vident le contenu, passent en brouillon et réutilisent la structure pour une prochaine ressource. On peut leur dire d'arrêter de faire ça mais d'une façon ou d'une autre, le portail A doit pouvoir à minima modifier/repasser en brouillon et idéalement supprimer sa ressource.
