### ISSUE TITLE
Console log not deleted within the code base

### ISSUE THREAD

**Issue by sfpmld** [betagouv/recommandations-collaboratives#646]
Hi there is nothing really important but I was looking around and found this `console.log`.
I imagine it was to be deleted after some debug session.
Have a nice day anyway

https://github.com/betagouv/recommandations-collaboratives/blob/e042a98387bff1e56e881ce25bb58ad01b3bc849/frontend_tests/cypress/e2e/project/collectivity/canSeeGeneralInformation.cy.js#L7

**Comment by glibersat** [comment]
Thanks for your input @sfpmld ! We will fix this quickly.
