### ISSUE TITLE
Changement de wording collectivité

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#684]
## Présentation - Colonne de droite
- [ ] Référent collectivité --> Référent porteur de projet
- [ ] Membres de la collectivité --> Porteur de projet et partenaires
- [ ] Inviter un membre de la collectivité --> Inviter ? et derrière si c'est un conseiller ou staff on met le bouton radio pour choisir comme dans la nvlle nav ? (si c'est un porteur de projet, il ne peut se toute façon pas inviter de conseiller)

## Paramètres - gestion des utilisateurs
- [ ] Membres de la collectivité --> Equipe du porteur de projet et partenaires
- [ ] Inviter un membre de la collectivité --> Inviter un membre porteur de projet ou un partenaire
- [ ] Invitations en attente de membres collectivité --> Invitations en attente porteur de projet et partenaires

## Autres pages
- [ ] EDL - Éléments renseignés par le porteur de projet
- [ ] Reco - Etiquette Non lu par la collectivité --> Non lu par le porteur de projet
- [ ] Conversation - colonne de droite - Membres de la collectivité --> Porteur de projet et partenaires
- [ ] Espace conseiller - bandeau jaune - "..., pas la collectivité" --> pas le porteur de projet.
- [ ] Page de modération - Equipe collectivité --> Porteur de projet

## Notifications 
- [ ] XX a invité YY en tant que collectivité --> en tant que porteur de projet

**Comment by Jeremy-Bojko** [comment]
## Présentation - Colonne de droite
* [ ]  Référent collectivité --> Référent porteur de projet
* [ ]  Membres de la collectivité --> Porteur de projet et partenaires
* [ ]  Inviter un membre de la collectivité --> Inviter ? et derrière si c'est un conseiller ou staff on met le bouton radio pour choisir comme dans la nvlle nav ? (si c'est un porteur de projet, il ne peut se toute façon pas inviter de conseiller)
 
 ## Paramètres - gestion des utilisateurs
* [ ]  Membres de la collectivité --> Equipe du porteur de projet et partenaires
* [ ]  Inviter un membre de la collectivité --> Inviter un membre porteur de projet ou un partenaire
* [ ]  Invitations en attente de membres collectivité --> Invitations en attente porteur de projet et partenaires

 ## Autres pages
 * [ ]  EDL - Éléments renseignés par le porteur de projet
* [ ]  Reco - Etiquette Non lu par la collectivité --> Non lu par le porteur de projet
* [ ]  Conversation - colonne de droite - Membres de la collectivité --> Porteur de projet et partenaires
* [ ]  Espace conseiller - bandeau jaune - "..., pas la collectivité" --> pas le porteur de projet.
* [ ]  Page de modération - Equipe collectivité --> Porteur de projet
 
 ## Notifications
 * [ ]  XX a invité YY en tant que collectivité --> en tant que porteur de projet
