### ISSUE TITLE
[Refonte Nav] Mettre à jour le tutoriel de la présentation d'un projet

### ISSUE THREAD

**Issue by Jeremy-Bojko** [betagouv/recommandations-collaboratives#747]

**Comment by sabinesafi** [comment]
@Jeremy-Bojko @Louifine si vous n'en avez pas déjà fini avec cette carte, ça serait bien de passer le tuto en bleu DSFR au passage
![Image](https://github.com/user-attachments/assets/7df167f6-072e-4e4d-9e9b-ab0bd0f22d70)
