### ISSUE TITLE
[MP] L'info qu'un projet est multipublié n'apparaît plus dans le kanban staff + rajouter l'info ailleurs

### ISSUE THREAD

**Issue by sabinesafi** [betagouv/recommandations-collaboratives#803]
- Dans le kanban du staff, l'info que le projet vient d'un autre portail ou a été publié sur un autre portail n'apparaît plus.
- Rajouter la mention de ce partage à plusieurs endroits : 
  - sur la page présentation, colonne de droite, entre les tags et la localisation (reprendre la même étiquette que dans le kanban du staff)
  - dans le fil d'activité du projet (en bas de la page Présentation), du CRM (fil général et projet) : Le projet XXX, initialement déposé sur le portail YYY, est maintenant également présent sur le portail ZZZ
  - sur le TDB conseillers vue liste, après Déposé le xxx (même ligne, même étiquette que dans le kanban)

**Comment by Jeremy-Bojko** [comment]
Première partie ok le reste est dispatché dans plusieurs issues, comme discuté ensemble
